/**
 * 3D Rotate Tool by YoFLA.com
 *
 * @author Matus Laco, www.yofla.com
 * @description Script for rotating images to provide a 3D look of an object
 * @sicne 06/2010
 * @updated 2015-08-16
 * @version 1.7.8
 * @homepage http://www.yofla.com/3d-rotate/
 *
 * @license : You many not delete/modify this license or authorship info
 * @license_type : ICONASYSENTERPRISEWL
 * @licensed_to :      Order Id: 4716
 * @authorized_domains : no limit on domains
 *
 * 3rd Party licenses:
 * Wave Pre-loader: MIT (https://github.com/tobiasahlin/SpinKit)
 *
 */

var RotateTool="object"===typeof RotateTool?RotateTool:{instances:{},isLogEnabled:!1,isLogToScreen:!1,isInitialized:!1,isTouchDevice:!1,isSupportedBrowser:null,isFullscreenBrowserAPISupported:!1,isCustomEventSupported:!1,isCanvasSupported:!1,isChrome:!1,authorizedDomains:"no limit on domains",scriptVersion:"1.7.8",licenseType:"ICONASYSENTERPRISEWL",eventsTouchStart:{forMouse:"mousedown",forTouch:"touchstart"},eventsTouchEnd:{forMouse:"mouseup",forTouch:"touchend"},eventsTouchMove:{forMouse:"mousemove",
forTouch:"touchmove"},eventsMouseOver:{forMouse:"mouseover",forTouch:void 0},eventsMouseOut:{forMouse:"mouseout",forTouch:void 0},eventsMouseLeave:{forMouse:"mouseleave",forTouch:void 0},listeners:[],ON_IMAGE:"3drt_on_image",ROTATION_START:"3drt_rotation_start",ROTATION_STOP:"3drt_rotation_stop",ZOOM_START:"3drt_zoom_start",ZOOM_STOP:"3drt_zoom_stop",ZOOM_CHANGE:"3drt_zoom_change",ZOOM_RESET:"3drt_zoom_reset",PAN_START:"3drt_pan_start",PAN_STOP:"3drt_pan_stop",TURN_START:"3drt_turning_start",TURN_STOP:"3drt_turning_stop",
HOTSPOT_HOVER:"3drt_hotspot_hover",HOTSPOT_HOVER_OUT:"3drt_hotspot_hover_out",HOTSPOT_OPEN:"3drt_hotspot_open",TOOLTIP_SHOW:"3drt_tooltip_show",TOOLTIP_HOVER:"3drt_tooltip_hover",TOOLTIP_HOVER_OUT:"3drt_tooltip_hover_out",PRELOADER_LOADED:"3drt_preloader_image_loaded",PRELOADER_PROGRESS:"3drt_preloader_progress",IMAGES_LOADED:"3drt_images_loaded",TOGGLE_ROTATE_MODE:"3drt_toggle_rotate_mode",TOGGLE_PAN_MODE:"3drt_toggle_pan_mode",MOUSEWHEEL_ZOOM:"3drt_mousewheel_zoom",CLICK_OBJECT:"3drt_click_object",
BUTTON_PLAY_PAUSE_CLICK:"3drt_button_play_pause_click",BUTTON_ARROW_LEFT_CLICK:"3drt_button_arrow_left_click",BUTTON_ARROW_RIGHT_CLICK:"3drt_button_arrow_right_click",BUTTON_FULLSCREEN_CLICK:"3drt_button_fullscreen_click",BUTTON_ZOOMSLIDER_CLICK:"3drt_button_zoomslider_click",BUTTON_ROTATE_CLICK:"3drt_button_toggle_rotate_click",BUTTON_PAN_CLICK:"3drt_button_toggle_pan_click",BUTTON_ZOOM_OUT_CLICK:"3drt_button_toggle_zoom_out_click",BUTTON_ZOOM_IN_CLICK:"3drt_button_toggle_zoom_in_click",BUTTON_START_CLICK:"3drt_start_click",
CONTEXMENU_SHOW:"3drt_contex-menu_show",zIndex:{images:5,imageShown:6,imageHidden:4,preloaderImage:9,preloader:10,customLayer:15,clickPane:20,buttons:30,hotspots:40,toolTip:50,overlay:100,hotspotImage:110,hotspotTitle:120,customLogo:130,contexMenu:150,info:900},initialize:function(){this.isInitialized||(this.defaultGAevents=[this.CLICK_OBJECT,this.BUTTON_PLAY_PAUSE_CLICK,this.BUTTON_ARROW_LEFT_CLICK,this.BUTTON_ARROW_RIGHT_CLICK,this.BUTTON_FULLSCREEN_CLICK,this.BUTTON_ZOOMSLIDER_CLICK,this.BUTTON_ROTATE_CLICK,
this.BUTTON_PAN_CLICK,this.HOTSPOT_HOVER,this.HOTSPOT_OPEN,this.CONTEXMENU_SHOW,this.ZOOM_START],this.addPolyFills(),this.isSupportedBrowser=this.supportedBrowserCheck(),this.isTouchDevice="ontouchstart"in document.documentElement,this.isFullscreenBrowserAPISupported=this.fullscreenBrowserCheck(),this.isRunningInIframe=this.isInIframe(),this.isCustomEventSupported=this.detectCustomEventSupport(),this.isCanvasSupported=this.detectCanvasSupport(),this.yofla_360_is_preview=!1,this.addDefaultStyleSheets(),
this.detectBrowser(),window.addEventListener?window.addEventListener("load",this.onPageLoaded,!1):window.attachEvent("onload",this.onPageLoaded),this.addGlobalFunctions(),this.isInitialized=!0)},addDefaultStyleSheets:function(){var a;a="div.rotate-tool-instance{";a+="}";a+="img.rotate-tool-image";a+="{";a+="    max-width: none;";a+="    vartical-align: none;";a+="    -moz-box-sizing: none;";a+="}";a+="div.rotate-tool-spacer{";a+="    background-image: url(https://www.yofla.com/cdn/rotatetool/spacer.gif);";
a+="    background-repeat: no-repeat";a+="}";a+="div.rotate-tool-hotspot-default{";a+="}";a+=".rotate-tool-unselectable{";a+="    -moz-user-select: none;";a+="    -webkit-user-select: none;";a+="    -ms-user-select: none;";a+="    user-select: none;";a+="    -webkit-user-drag: none;";a+="    user-drag: none;";a+="}";a+="\t\t.yp_wave {";a+="\t\t\tmargin: 100px auto;";a+="\t\t\twidth: 50px;";a+="\t\t\theight: 30px;";a+="\t\t\ttext-align: center;";a+="\t\t\tfont-size: 10px;";a+="\t\t}";a+="\t\t.yp_wave > div {";
a+="\t\t\tbackground-color: #333;";a+="\t\t\theight: 100%;";a+="\t\t\twidth: 6px;";a+="\t\t\tdisplay: inline-block;";a+="\t\t\t-webkit-animation: stretchdelay 1.2s infinite ease-in-out;";a+="\t\t\tanimation: stretchdelay 1.2s infinite ease-in-out;";a+="\t\t}";a+="\t\t.yp_wave .rect2 {";a+="\t\t\t-webkit-animation-delay: -1.1s;";a+="\t\t\tanimation-delay: -1.1s;";a+="\t\t}";a+="\t\t.yp_wave .rect3 {";a+="\t\t\t-webkit-animation-delay: -1.0s;";a+="\t\t\tanimation-delay: -1.0s;";a+="\t\t}";a+="\t\t.yp_wave .rect4 {";
a+="\t\t\t-webkit-animation-delay: -0.9s;";a+="\t\t\tanimation-delay: -0.9s;";a+="\t\t}";a+="\t\t.yp_wave .rect5 {";a+="\t\t\t-webkit-animation-delay: -0.8s;";a+="\t\t\tanimation-delay: -0.8s;";a+="\t\t}";a+="\t\t@-webkit-keyframes stretchdelay {";a+="\t\t\t0%, 40%, 100% { -webkit-transform: scaleY(0.4) }";a+="\t\t20% { -webkit-transform: scaleY(1.0) }";a+="\t\t}";a+="\t\t@keyframes stretchdelay {";a+="\t\t\t0%, 40%, 100% {";a+="\t\t\t\ttransform: scaleY(0.4);";a+="\t\t\t-webkit-transform: scaleY(0.4);";
a+="\t\t} 20% {";a+="\t\t\ttransform: scaleY(1.0);";a+="\t\t\t-webkit-transform: scaleY(1.0);";a+="\t\t\t}";a+="\t\t}";a+="span.rotate-tool-tooltip{";a+="    font-family: sans-serif;";a+="    font-size: 13px;";a+="    color: #0c0c0c;";a+="    padding: 5px;";a+="    opacity: 0.85;";a+="    filter: Alpha(Opacity=85);";a+="    border-radius: 5px;";a+="    border: 1px solid gray;";a+="    background-color: rgba(230,230,230,0.5);";a+="}";a+="ul.rotate-tool-contex-menu {";a+="border:0px solid #666;";a+=
"min-width:150px;";a+="max-width:350px;";a+="list-style:none;";a+="padding:0;";a+="margin:0;";a+="cursor:pointer;";a+="}";a+="ul.rotate-tool-contex-menu li {";a+="text-align:left;";a+="padding:3px 10px 3px 5px;";a+="margin:0;";a+="cursor:pointer;";a+='font-family: "Lucida Grande", Verdana, Arial, "Bitstream Vera Sans", sans-serif;';a+="text-decoration:none;";a+="color:#fff;";a+="font-size:12px;";a+="border-top:1px solid #fff;";a+="border-left:1px solid #fff;";a+="border-bottom:1px solid #999;";a+=
"border-right:1px solid #999;";a+="background-color: rgba(0,0,0,.7);";a+="}";a+="ul.rotate-tool-contex-menu li.selected,";a+="ul.rotate-tool-contex-menu li:hover {";a+="color:#fff;";a+="background-color: rgba(56,117,215,.7);";a+="cursor:pointer;";a+="}";a+="ul.rotate-tool-contex-menu li.selected:hover {";a+="color:#333;";a+="background-color:#eee;";a+="cursor:pointer;";a+="}";a+="ul.rotate-tool-contex-menu li.disabled,";a+="ul.rotate-tool-contex-menu li:hover.disabled {";a+="background-color: #eee;";
a+="color:#999;";a+="cursor:pointer;";a+="}";var e=document.getElementsByTagName("head")[0],b=document.createElement("style");b.type="text/css";b.styleSheet?b.styleSheet.cssText=a:b.appendChild(document.createTextNode(a));e.appendChild(b)},onPageLoaded:function(){RotateTool.execRotateTool()},execRotateTool:function(){if(!1!=RotateTool.isObjectEmpty(RotateTool.instances)&&document.querySelectorAll)for(var a=document.querySelectorAll("[data-rotate-tool]"),e,b,d,c,g=0;g<a.length;g++){e=a[g];b=e.getAttribute("data-rotate-tool");
c=e.getAttribute("id");c||(c="rotate-tool-instance-id-"+Math.round(1E4*Math.random()),e.setAttribute("id",c));try{d=this.parseJSON(b)}catch(k){this.reportUserError('Error parsing data in element with id "'+c+'" : '+k);break}e={target:c,path:d.path,id:d.id,mode:d.mode,configFile:d.configFile,themeUrl:d.themeUrl,size:d.size,gaData:d.gaData?d.gaData:{}};this.add(e)}},createInstance:function(a){if("undefined"===typeof this.instances[a.target]&&(this.instances[a.target]=this.rotateToolFactory(a),"function"===
typeof window.yofla_rotateToolInstanceInitialized))try{window.yofla_rotateToolInstanceInitialized(a.target)}catch(e){}},createPopupLink:function(a){document.getElementById(a.target)},add:function(a){this.isInitialized||this.initialize();var e=this.validateRotationData(a);!0===e?"popup"==a.mode?this.createPopupLink(a):this.createInstance(a):this.reportUserError(e)},get:function(a){return a?(a=this.instances[a])?a:null:this.getAnonymousInstance()},getInstances:function(){return this.instances},getAnonymousInstance:function(){var a,
e;for(e in this.instances){a=this.instances[e];break}return a},reportUserError:function(a){alert("RotateTool Error: "+a)},log:function(a,e){this.isLogEnabled&&-1<this.logLevel.indexOf(a)&&("undefined"===typeof console||!0===this.isLogToScreen?this.logToScreen(e,a):console.log(e))},logToScreen:function(a,e){this.logTarget?this.logTarget.innerHTML=a.toString()+"<br />"+this.logTarget.innerHTML:this.createLogTarget()},createLogTarget:function(){var a=this.get();a&&a.target&&(this.logTarget=document.createElement("div"),
this.logTarget.className="rotate-tool-log-target",this.logTarget.style.position="absolute",this.logTarget.style.width="50%",this.logTarget.style.height="50%",this.logTarget.style.border="1px solid red;",this.logTarget.style.zIndex=999,this.logTarget.style.backgroundColor="yellow",this.logTarget.style.opacity="0.65",this.logTarget.style.filter="alpha(Opacity=65)",this.logTarget.style.overflow="hidden",this.logTarget.style.color="black",this.logTarget.style.fontSize="11px",this.logTarget.style.textAlign=
"left",this.logTarget.innerHTML="test",a.target.appendChild(this.logTarget))},validateRotationData:function(a){return a.target?!0:"Target not defined!"},rotateToolFactory:function(a){var e={THRESHOLD_TIME_ROTATE_PAN_DIF:250,THRESHOLD_TIME_DRAG_STOP_ROTATE:100,elementId:a.target,target:document.getElementById(a.target),path:a.path,configFile:a.configFile?a.configFile:"config.js",isConfigJsLoaded:!1,productId:a.id,themeUrl:a.themeUrl,forcedSize:a.size,settings:{},originalTargetWidth:null,originalTargetHeight:null,
originalTargetRatio:null,targetWidth:400,targetHeight:300,targetRation:null,zIndex:{},buttons:{},vSteps:null,hSteps:null,imageNodes:null,rotateIntervalDuration_original:null,rotateIntervalDuration_current:null,rotateIntervalThresholdStop:null,rotateInterval:null,rotateImages:[],imagesGrid:[],lastImgH:null,lastImgV:null,newImgH:null,newImgV:null,dx:0,dy:0,previousDx:0,isRotating:!1,wasRotating:!1,currentImage:null,previousImage:null,rotateOnceCounter:0,timeLastImageShown:0,durationMultiplier:1,isZoomed:!1,
scaleInPercent:100,relativeX:0.5,relativeY:0.5,isRotationWhenZoomed:!1,zoomStepInPercent:100,zoomStepInRatio:100,zoomSteps:4,objectWidth:400,objectHeight:400,dragInterval:null,touchStart:null,touchMove:null,touchMovePrevious:null,touchMovePreviousDrag:null,isGestureStart:!1,gestureStartValue:null,lastYatDyChange:null,touchEnd:null,mouseWheelZooms:!1,currentZoomValue:0,zoomInPercent:100,isMouseMoved:!1,imageLoadErrorsString:"",imageLoadErrorCount:0,imagesToLoad:null,imagesLoaded:null,imagesProcessed:null,
isImagesLoaded:!1,preloader:null,usingSmallImages:null,startButtonToggled:!1,hotspotInstances:null,activeHotspot:null,hotspotOverlay:null,hotspotImage:null,isHotspotsVisible:!0,tooltips:{},daggedObject:null,clickPaneTouchMoveReference:null,clickPaneTouchEndReference:null,requestRescaleFlag:!1,mouseWheelCounter:0,clickPane:null,sliderHandle:null,handleMaxX:null,infoPanel:null,isGAenabled:a.gaData.isEnabled&&"true"==a.gaData.isEnabled.toLowerCase(),gaEnabledEvents:a.gaData.enabledEvents instanceof Array?
a.gaData.enabledEvents:RotateTool.defaultGAevents,gaTrackingId:a.gaData.trackingId,gaCategory:a.gaData.category,gaLabel:a.gaData.label,setLevel:function(b){!1!==this.isImagesLoaded&&(this.lastImgV=b,b=this.dx,this.dx=this.dy=0,this.showNextImage(),this.dx=b)},setImage:function(b,d){d="undefined"!==typeof d?d:!0;if(!isNaN(b)&&!1!==this.isImagesLoaded){var a=this.dx;this.stopRotation();b>this.imagesToLoad-1||(1==this.vSteps||b<this.hSteps?this.lastImgH=b:(this.lastImgV=Math.floor(b/this.hSteps),this.lastImgH=
b-this.lastImgV*this.hSteps),this.dx=this.dy=0,this.showNextImage(d),this.dx=a)}},startLoadingImages:function(){this.startButtonToggled=!0;this.generateImages()},isSpinning:function(){return 0!=this.dx},getImageId:function(){return this.currentImage.idNumber},toggleHotspots:function(){this.isHotspotsVisible?this.showHotspots(!1):this.showHotspots(!0)},showHotspots:function(b){this.isHotspotsVisible=b?!0:!1;this.redrawHotspots()},initialize:function(){if(this.target){this.path=RotateTool.fixPathVariable(this.path);
var b=this.path+this.configFile;this.zIndex=RotateTool.zIndex;this.setDefaultTargetStyles();this.loadStyles(this.themeUrl);this.storeTargetDimensions();this.target.innerHTML="";this.gaCategory=this.gaCategory&&""!=this.gaCategory?this.gaCategory:"YOFLA_360";var d=this.productId?this.productId:this.elementId;this.gaLabel=this.gaLabel&&""!==this.galabel?this.gaLabel:"YOFLA_360_"+d;!1===RotateTool.isSupportedBrowser?this.reportBrowserNotSupported():"config.xml"==this.configFile?RotateTool.loadXMLFile(b,
this.configXmlLoaded,this):RotateTool.loadScript(b,this.configJsLoaded,this)}else RotateTool.reportUserError("Could not locate target element with id:"+a.target)},setDefaultTargetStyles:function(){this.target.style.position="relative";this.target.style.minWidth="150px";this.target.style.minHeight="150px";this.target.style.overflow="hidden";this.target.className="rotate-tool-instance";this.target.className+=" rotate-tool-spacer";this.target.className+=" rotate-tool-unselectable";RotateTool.isTouchDevice&&
(this.target.className+=" rotate-tool-touch-device");this.originalTargetWidth=this.target.clientWidth;this.originalTargetHeight=this.target.clientHeight;this.originalTargetRatio=this.originalTargetWidth/this.originalTargetHeight;if("undefined"===typeof this.forcedSize?0:2==this.forcedSize.length){var b=parseInt(this.forcedSize[0]),d=parseInt(this.forcedSize[1]);this.target.style.width=b+"px";this.target.style.height=d+"px";this.target.style.minWidth=b+"px";this.target.style.minHeight=d+"px";this.originalTargetWidth=
b;this.originalTargetHeight=d;this.originalTargetRatio=b/d}this.updateTargetStyles()},updateTargetStyles:function(){var b="undefined"===typeof this.forcedSize?!1:2==this.forcedSize.length?!0:!1;RotateTool.isFullscreen()?(this.target.style.width="100%",this.target.style.height="100%"):RotateTool.isRunningInIframe&&!1==b?(this.target.style.width="100%",this.target.style.height="100%"):document.documentElement.clientWidth<this.originalTargetWidth?(this.target.style.width=document.documentElement.clientWidth+
"px",this.target.style.height=Math.floor(document.documentElement.clientWidth/this.originalTargetRatio)+"px"):(this.target.style.width=this.originalTargetWidth+"px",this.target.style.height=this.originalTargetHeight+"px");this.storeTargetDimensions()},storeTargetDimensions:function(){this.targetWidth=Math.min(this.target.clientWidth,document.documentElement.clientWidth);this.targetHeight=Math.max(200,this.target.clientHeight);this.objectWidth=Math.floor(this.targetWidth);this.objectHeight=Math.floor(this.targetHeight);
this.targetRatio=this.targetWidth/this.targetHeight},loadStyles:function(b){var d=document;"undefined"===typeof b?b=this.path+"assets/styles.css":0<b.indexOf("styles.css")||(b=RotateTool.fixPathVariable(b)+"styles.css");if(!d.getElementById("rotate-tool-styles")){var a=d.getElementsByTagName("head")[0],d=d.createElement("link");d.id="rotate-tool-styles";d.rel="stylesheet";d.type="text/css";d.href=b;d.media="all";a.appendChild(d)}},setInfo:function(){var b=this.createInfoIcon();this.target.appendChild(b);
RotateTool.addClickOrTouchListener(b,{forTouch:"touchend",forMouse:"click"},function(){window.open("//www.yofla.com/3d-rotate/player-about/?ref=player_trial","_blank")})},createInfoIcon:function(){var b=document.createElement("div");b.className="rotate-tool-info-image";b.style.position="absolute";b.style.top="5px";b.style.left="5px";b.style.width="25px";b.style.height="25px";b.style.cursor="pointer";b.style.border="0px";b.style.zIndex=this.zIndex.info;b.style.backgroundImage="url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABkAAAAZCAMAAADzN3VRAAAAaVBMVEUAAADq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urm39/i1NTeycnbvr3TpqXPmZjLjIrHf33EcG7BYl+9Uk65QDq1LCKxGQIgeu/UAAAAInRSTlMAARMVFzAyPVRqi4ysrrK9wsvP2ubo6evt8PLz9ff4+vz9cPxJuAAAANBJREFUKM99UtkOhCAMrDfeit31dpH//8gVBKqJcZ5aJqXTaQFOhCyreMerjIVwRZDWaFGnARFxgVcUsSWSFu9ok5OIuHn4ztu+6ohHivBLQ4y7PNDruPQBvNT+oYnFJKkHQWOZWcrfaJMmAIbPYJBTMi7CtDmQQ2XDQag+7rsK+E2AHGzKobPhJEj0gY5qcFMMUo3rg6pGIPUhbapkQ9Lm5ukVM1/mcR4MumYgD5xvk1a9km/Oa80Io1p57fbTC7mNH7zs52WnL3fwcjuP9/YHpzIqZ7oB1g0AAAAASUVORK5CYII=')";
return b},addContexMenu:function(){this.addContexMenuListener();this.addContexMenuContainer();this.setContexMenuItems(this.getContexMenuItems())},getContexMenuItems:function(){var b=[],d={title:"Disable this menu",action:"CONTEXMENU_DISABLE",data:null},a=this.getCustomContexMenuItems();0<a.length&&(b=a.concat(b));if("3DRTFLEXIPRO"==RotateTool.licenseType||"3DRTFLEXIPROWL"==RotateTool.licenseType)a=RotateTool.getCurrentDomain().toLocaleLowerCase(),0<a.length&&0>RotateTool.authorizedDomains.indexOf(a)&&
"localhost"!==a&&b.unshift({title:"Domain not authorized!",action:"URL_OPEN",data:"http://www.yofla.com/3d-rotate/support/domain-not-authorized/"});0<b.length&&b.push(d);return b},getCustomContexMenuItems:function(){var b=[],d,a;if(this.settings.custom&&this.settings.custom.contexMenu)for(d=this.settings.custom.contexMenu.items,i=0;i<d.length;i++)(a=d[i])&&a.title&&0<a.title.length&&b.push(a);return b},addContexMenuListener:function(){var b=this;this.funcRefContexMenuShow=function(d){d.preventDefault();
b.showContexMenu(d)};this.funcRefContexMenuShowIE=function(){window.event.returnValue=!1;b.showContexMenu(window.event)};this.target.addEventListener?this.target.addEventListener("contextmenu",this.funcRefContexMenuShow,!1):this.target.attachEvent("oncontextmenu",this.funcRefContexMenuShowIE)},disableContexMenu:function(){this.target.addEventListener?this.target.removeEventListener("contextmenu",this.funcRefContexMenuShow,!1):this.target.detachEvent("oncontextmenu",this.funcRefContexMenuShowIE)},
addContexMenuContainer:function(){this.contexMenu=document.createElement("ul");this.contexMenu.style.zIndex=this.zIndex.contexMenu;this.contexMenu.style.position="absolute";this.contexMenu.style.display="none";this.contexMenu.style.left="100px";this.contexMenu.style.top="100px";this.contexMenu.className="rotate-tool-contex-menu";this.target.appendChild(this.contexMenu);RotateTool.addClickOrTouchListener(this.contexMenu,RotateTool.eventsMouseLeave,RotateTool.bind(this,this.hideContexMenu))},setContexMenuItems:function(b){this.contexMenu.innerHTML=
"";for(var d=this,a,g,e,f=0;f<b.length;f++)a=document.createElement("li"),g=b[f],e=function(b){return function(a){d.onContexMenuItemSelected(a,b)}}(g),a.innerHTML=g.title,RotateTool.addClickOrTouchListener(a,{forMouse:"click"},e),this.contexMenu.appendChild(a)},onContexMenuItemSelected:function(b,a){this.hideContexMenu();switch(a.action){case "URL_OPEN":window.open(a.data,"_blank");break;case "CONTEXMENU_DISABLE":this.disableContexMenu()}},showContexMenu:function(b){this.dispatchEvent(RotateTool.CONTEXMENU_SHOW);
var a;try{a=RotateTool.getLocalMousePosition(b)}catch(c){}isNaN(a.x)||isNaN(a.y)||(this.contexMenu.style.display="block",this.contexMenu.style.left=a.x+"px",this.contexMenu.style.top=a.y+"px")},hideContexMenu:function(){this.contexMenu&&(this.contexMenu.style.display="none")},configJsLoaded:function(){RotateTool.yofla_360_is_preview=0<navigator.userAgent.indexOf("AdobeAIR")?!0:!1;if(!this.isConfigJsLoaded){this.isConfigJsLoaded=!0;var b;try{b=eval("productRotationData_"+this.productId)}catch(a){try{b=
eval("RotationData_"+this.productId)}catch(c){try{b=eval("RotationData")}catch(g){return RotateTool.reportUserError("Error evaluating config.js!"),!1}}}if(void 0===b)return RotateTool.reportUserError("Error accessing settings in config.js!"),!1;try{this.parseSettings(b)}catch(e){RotateTool.reportUserError("Error parsing settings, maybe a typo? Error: "+e)}}},onSettingsInitialized:function(){this.addWindowResizeListener();this.addFullscreenListener();this.initCustomLogo();this.addContexMenu();this.initHotspots();
this.initRotation()},configXmlLoaded:function(b){var a={settings:{rotation:{multilevel:{}},preloader:{},userInterface:{},control:{},hotspots:{}},images:{}},c=b[0].getElementsByTagName("settings")[0],g={rotatePeriod:parseFloat(c.getElementsByTagName("rotation")[0].getAttribute("rotatePeriod")),rotate:c.getElementsByTagName("rotation")[0].getAttribute("rotate"),rotateDirection:parseInt(c.getElementsByTagName("rotation")[0].getAttribute("rotateDirection")),bounce:"true"==c.getElementsByTagName("rotation")[0].getAttribute("bounce"),
multilevel:{}};a.settings.rotation=g;g={showToggleRotateButton:"true"==c.getElementsByTagName("userInterface")[0].getAttribute("showToggleRotateButton"),showTogglePlayButton:"true"==c.getElementsByTagName("userInterface")[0].getAttribute("showTogglePlayButton"),showZoombar:"true"==c.getElementsByTagName("userInterface")[0].getAttribute("showZoombar"),showArrows:"true"==c.getElementsByTagName("userInterface")[0].getAttribute("showArrows"),showToggleFullscreenButton:"true"==c.getElementsByTagName("userInterface")[0].getAttribute("showToggleFullscreenButton"),
showMouseWheelToolTip:"true"==c.getElementsByTagName("userInterface")[0].getAttribute("showMouseWheelToolTip"),showZoomButtons:"true"==c.getElementsByTagName("userInterface")[0].getAttribute("showZoomButtons")};a.settings.userInterface=g;g={maxZoom:parseInt(c.getElementsByTagName("control")[0].getAttribute("maxZoom")),maxZoomAuto:"true"==c.getElementsByTagName("control")[0].getAttribute("maxZoomAuto"),reverseDrag:"true"==c.getElementsByTagName("control")[0].getAttribute("reverseDrag"),enableSwing:"true"==
c.getElementsByTagName("control")[0].getAttribute("enableSwing"),mouseWheelZooms:"true"==c.getElementsByTagName("control")[0].getAttribute("mouseWheelZooms")};a.settings.control=g;c={image:c.getElementsByTagName("preloader")[0].getAttribute("image")};a.settings.preloader=c;c=b[0].getElementsByTagName("images")[0];0==c.getElementsByTagName("image").length&&(c=b[0].getElementsByTagName("images")[1]);b=c.getElementsByTagName("image");for(var c=b.length,g=[],e=0;e<c;e++){var f={},h,l;h=b[e].getAttribute("src");
l=b[e].getAttribute("srcLarge");f.src=h;l&&(f.srcLarge=l);g.push(f)}a.images=g;this.parseSettings(a)},parseSettings:function(b){this.settings.rotation={rotatePeriod:b.settings.rotation.rotatePeriod,rotateOnStart:"true"==b.settings.rotation.rotate,rotateDirection:b.settings.rotation.rotateDirection,bounce:b.settings.rotation.bounce,rotateOnce:"once"==b.settings.rotation.rotate,multilevel:{}};this.bounce=this.settings.rotation.bounce;try{this.settings.rotation.multilevel.verticalSensitivity=b.settings.rotation.multilevel.verticalSensitivity}catch(a){this.settings.rotation.multilevel.verticalSensitivity=
5}this.settings.preloader={type:"undefined"===typeof b.settings.preloader.type?"default":b.settings.preloader.type,color1:"undefined"===typeof b.settings.preloader.color1?"#333333":b.settings.preloader.color1,image:"undefined"===typeof b.settings.preloader.image?"first":b.settings.preloader.image,showStartButton:"undefined"===typeof b.settings.preloader.showStartButton?!1:b.settings.preloader.showStartButton,background:"undefined"===typeof b.settings.preloader.background?{enabled:!0,alpha:0.5,color:"#FFFFFF"}:
b.settings.preloader.background};this.settings.userInterface={showTogglePlayButton:b.settings.userInterface.showTogglePlayButton,showZoomButtons:b.settings.userInterface.showZoomButtons,showArrows:b.settings.userInterface.showArrows,showToggleFullscreenButton:b.settings.userInterface.showToggleFullscreenButton,showToggleRotateButton:b.settings.userInterface.showToggleRotateButton,showMouseWheelToolTip:"undefined"===typeof b.settings.preloader.showMouseWheelToolTip?!0:b.settings.preloader.showMouseWheelToolTip,
showZoomSlider:b.settings.userInterface.showZoombar};!1==this.settings.userInterface.showMouseWheelToolTip&&(this.toolTipOnMouseWheelShown=!0);this.settings.control={maxZoom:b.settings.control.maxZoom?b.settings.control.maxZoom:200,maxZoomAuto:"undefined"===typeof b.settings.control.maxZoomAuto?!1:b.settings.control.maxZoomAuto,dragSpeed:b.settings.control.dragSpeed,reverseDrag:b.settings.control.reverseDrag,enableSwing:b.settings.control.enableSwing,rotateOnMouseHover:b.settings.control.rotateOnMouseHover,
clickUrl:b.settings.control.clickUrl,clickUrlTarget:b.settings.control.clickUrlTarget,touchPageScroll:"undefined"===typeof b.settings.control.touchPageScroll?!1:b.settings.control.touchPageScroll,disableMouseControl:b.settings.control.disableMouseControl,mouseWheelZooms:b.settings.control.mouseWheelZooms};this.settings.hotspots=b.hotspots;this.hSteps=this.imagesToLoad=b.images.length;this.vSteps=1;try{this.vSteps=b.settings.rotation.multilevel.verticalSteps}catch(c){}"undefined"===typeof this.vSteps&&
(this.vSteps=1);this.hSteps=this.imagesToLoad/this.vSteps;this.imageNodes=b.images;this.settings.hotspots=b.hotspots;this.settings.custom=b.custom;this.zoomStepInPercent=Math.round(this.settings.control.maxZoom/this.zoomSteps);this.zoomStepInRatio=1/this.zoomSteps;this.settings.stylesVersion=0;b.stylesVersion&&(this.settings.stylesVersion=parseInt(b.stylesVersion));this.onSettingsInitialized()},setLargeImagesSize:function(b,a){this.largeImagesSize={width:b,height:a};this.updateMaxZoom()},updateMaxZoom:function(){if(this.settings.control.maxZoomAuto){var b=
this.computeMaxZoomAuto();this.settings.control.maxZoom=b}},computeMaxZoomAuto:function(){return Math.max(100,100*(1/(this.targetRatio<this.currentImage.ratio?this.targetWidth/this.currentImage.originalWidth:this.targetHeight/this.currentImage.originalHeight)))},addWindowResizeListener:function(){var b=this;this.resizeListenerReference=function(a){b.windowResizeListener(a)};RotateTool.addEventSimple(window,"resize",this.resizeListenerReference)},addFullscreenListener:function(){document.addEventListener&&
(document.addEventListener("fullscreenchange",RotateTool.bind(this,this.fullscrentChangedListener)),document.addEventListener("webkitfullscreenchange",RotateTool.bind(this,this.fullscrentChangedListener)),document.addEventListener("mozfullscreenchange",RotateTool.bind(this,this.fullscrentChangedListener)),document.addEventListener("MSFullscreenChange",RotateTool.bind(this,this.fullscrentChangedListener)))},initRotation:function(){this.updateTargetStyles();this.showPreloaderImage(this.settings.preloader.image,
this.generateImages)},showPreloaderImage:function(b,a){var c,g;if(RotateTool.isIE8)a.apply(this);else if(isNaN(b))switch(b){case "first":c=this.path+this.imageNodes[0].src;this.createPreloaderImage(c,a);break;case "splash":c=this.path+"splash.jpg";this.createPreloaderImage(c,a);break;case "splash.png":c=this.path+"splash.png";this.createPreloaderImage(c,a);break;default:a.apply(this)}else g=parseInt(b),g<this.imageNodes.length?(c=this.path+this.imageNodes[g].src,this.imageNodes[g].srcLarge&&600<this.targetWidth&&
(c=this.path+this.imageNodes[g].srcLarge),this.createPreloaderImage(c,a)):a.apply(this)},createPreloaderImage:function(b,a){var c=document.createElement("img");this.target.appendChild(c);c.className="rotate-tool-preloader-image";c.style.position="absolute";c.style.display="block";c.style.visibility="hidden";c.style.zIndex=this.zIndex.preloaderImage;c.onload=this.preloaderImageLoaded.apply(this,[c,a]);c.onerror=null;c.src=b;this.preloaderImage=c},preloaderImageLoaded:function(b,a){var c=this;return function(){c.processLoadedPreloaderImage(b,
a)}},processLoadedPreloaderImage:function(b,a){this.dispatchEvent(RotateTool.PRELOADER_LOADED);b.scaled=!1;b.ratio=b.width/b.height;b.originalWidth=b.width;b.originalHeight=b.height;b.style.visibility="visible";this.setScale(100,b);a.apply(this)},generateImages:function(){if(!0==this.settings.preloader.showStartButton&&!1==this.startButtonToggled)this.showStartButton();else{this.addPreloader(this.settings.preloader.type);for(var b=0,a=0;a<this.imagesToLoad;a++){var c,g,e;c=this.path+this.imageNodes[a].src;
g=this.imageNodes[a].srcLarge?this.path+this.imageNodes[a].srcLarge:!1;e=this.imageNodes[a].srcSmall?this.path+this.imageNodes[a].srcSmall:!1;var f=document.createElement("img");f.id="rotate-image-"+a;f.idNumber=a;f.className="rotate-tool-image";f.fileName=RotateTool.baseName(c);void 0===this.imagesGrid[b]&&(this.imagesGrid[b]=[]);this.imagesGrid[b].push(a);f.data=this.imageNodes[a];f.hotspots=this.processImageDataHotspots(f.data.hotspots);f.srcNormal=c;f.srcLarge=g;f.srcSmall=e;f.style.display="block";
f.style.zIndex=this.zIndex.imageHidden;f.onload=this.imageLoaded.apply(this,[f]);f.onerror=this.imageError.apply(this,[f]);this.rotateImages[a]=f;RotateTool.isChrome||(e?(f.src=e,this.usingSmallImages=!0):(f.src=c,this.usingSmallImages=!1));0===(a+1)%this.hSteps&&b++}RotateTool.isChrome&&(b=this.rotateImages[0],b.src=b.srcNormal,this.usingSmallImages=!1)}},showStartButton:function(){return this.generateButton("rotate-tool-button-start",this.startButtonClickListener)},startButtonClickListener:function(b){this.dispatchEvent(RotateTool.BUTTON_START_CLICK);
b.target.style.display="none";this.startLoadingImages()},addPreloader:function(b){switch(b){case "wave":RotateTool.browserSupportsCSSProperty("animation")?this.preloader=RotateTool.wavePreloader(this.elementId,this.settings.preloader):this.preloader=RotateTool.defaultPreloader(this.elementId,this.settings.preloader);break;default:this.preloader=RotateTool.defaultPreloader(this.elementId,this.settings.preloader)}},processImageDataHotspots:function(b){var a=null;if(!RotateTool.isObjectEmpty(b)){var a=
[],c;for(c in b){var g={};g.id=b[c].id;g.rx=b[c].rx;g.ry=b[c].ry;a.push(g)}}return a},imageLoaded:function(b){var a=this;return function(){a.imagesLoaded++;a.processLoadedImage(b);a.increaseImagesProcessedCount();RotateTool.isChrome&&a.loadNextImage()}},loadNextImage:function(){var b=this.rotateImages[this.imagesLoaded];b&&(b.src=b.srcNormal)},imageNormalLoaded:function(b){var a=this;return function(){a.processLoadedImageNormal(b)}},loadLargeImage:function(b,a){if(!0!==this.isLoadingLargeImage){this.isLoadingLargeImage=
!0;var c=document.createElement("img");c.onload=this.imageLargeLoaded.apply(this,[c,b]);c.src=b.srcLarge}},imageLargeLoaded:function(b,a){var c=this;return function(){c.processLoadedImageLarge(b,a)}},imageError:function(b){var a=this;return function(){a.imageLoadErrorsString+=b.src+"\n";a.imageLoadErrorCount+=1;a.increaseImagesProcessedCount()}},increaseImagesProcessedCount:function(){this.imagesProcessed++;this.updatePreloader();this.checkImagesProcessed()},checkImagesProcessed:function(){if(this.imagesProcessed==
this.imagesToLoad){this.destroyPreloader();if(this.imagesLoaded==this.imagesToLoad)this.onAllImagesSuccesfullyLoaded();this.preloaderImage&&(this.preloaderImage.style.display="none")}},updatePreloader:function(){var b=Math.round(100*(this.imagesProcessed/this.imagesToLoad));this.preloader&&this.preloader.update&&this.preloader.update(b);this.dispatchEvent(RotateTool.PRELOADER_PROGRESS,parseInt(b))},destroyPreloader:function(){this.preloader&&this.preloader.destroy&&this.preloader.destroy()},processLoadedImage:function(b){this.target.appendChild(b);
b.style.position="absolute";b.style.zIndex=this.zIndex.imageHidden;b.style.overflow="hidden";!0==this.settings.control.disableMouseControl?(b.style.pointerEvents="none",b.setAttribute&&b.setAttribute("draggable","false")):b.style.cursor="pointer";b.scaled=!1;b.ratio=b.width/b.height;b.originalWidth=b.width;b.originalHeight=b.height;b.normalImageWidth=b.width;b.normalImageHeight=b.height;b.onload=null;this.setScale(100,b)},processLoadedImageNormal:function(b){var a=this.rotateImages[b.id];a.originalWidth=
a.width;a.originalHeight=a.height;a.normalImageWidth=a.width;a.normalImageHeight=a.height;a.scaled=!1;a.onload=null;a.src=b.src},processLoadedImageLarge:function(b,a){this.isLoadingLargeImage=!1;a.src=b.src;a.originalWidth=b.width;a.originalHeight=b.height;a.largeImageWidth=b.width;a.largeImageHeight=b.height;a.scaled=!1;a.onload=null;this.setScale(this.scaleInPercent,a);setTimeout(RotateTool.bind(this,this.loadNextImage),200);this.largeImagesSize||this.setLargeImagesSize(b.width,b.height)},loadNextLargeImage:function(){var b=
this.getNextUnloadedLargeImage();b&&this.loadLargeImage(b)},getNextUnloadedLargeImage:function(){if(!this.currentImage.srcLarge)return!1;for(var b,a=0;a<this.hSteps;a++)if(b=this.rotateImages[this.imagesGrid[this.newImgV][a]],b.srcLarge&&"undefined"==typeof b.largeImageWidth)return b;for(a=0;a<this.rotateImages.length;a++)if(b=this.rotateImages[a],b.srcLarge&&"undefined"==typeof b.largeImageWidth)return b;return!1},onAllImagesSuccesfullyLoaded:function(){this.dispatchEvent(RotateTool.IMAGES_LOADED,
this.imagesLoaded);this.isImagesLoaded=!0;if("function"===typeof window.rotateToolInstanceLoaded)try{window.rotateToolInstanceLoaded(this.elementId)}catch(b){}if("function"===typeof window.yofla_rotateToolInstanceLoaded)try{window.yofla_rotateToolInstanceLoaded(this.elementId)}catch(a){}this.onImagesInitialized()},initLoadedImages:function(){for(var b=0;b<this.rotateImages.length;b++);setTimeout(RotateTool.bind(this,this.onImagesInitialized),250)},hideAllImages:function(){for(var b=0;b<this.rotateImages.length;b++)this.rotateImages[b].style.visibility=
"hidden"},onImagesInitialized:function(){this.hideAllImages();this.customLayer=document.createElement("div");this.customLayer.className="rotate-tool-custom-layer";this.customLayer.style.zIndex=this.zIndex.customLayer;this.target.appendChild(this.customLayer);this.addControls();this.initRotationVariables();this.setFirstImage();this.showNextImage();window.requestAnimationFrame?this.rotateLoop():this.rotateInterval=setInterval(RotateTool.bind(this,this.rotateLoop),17);this.settings.rotation.rotateOnStart||
this.settings.rotation.rotateOnce?this.startRotation():this.dx=0;this.usingSmallImages&&setTimeout(RotateTool.bind(this,this.loadNormalImages),150)},setFirstImage:function(){var b=this.settings.preloader.image,a;"first"===b&&(b=0);"number"==typeof b&&(1==this.vSteps?b<this.hSteps&&(this.lastImgH=b-this.dx):(a=b%this.hSteps,b=Math.floor(b/this.hSteps),this.lastImgH=a-this.dx,this.lastImgV=b,this.dy=0))},loadNormalImages:function(){for(var b=0;b<this.rotateImages.length;b++){var a=document.createElement("img");
a.id=b;a.onload=this.imageNormalLoaded.apply(this,[a]);a.src=this.rotateImages[b].srcNormal}},initRotationVariables:function(){this.rotateIntervalDuration_current=this.rotateIntervalDuration_original=Math.floor(1E3*this.settings.rotation.rotatePeriod/this.hSteps);this.rotateIntervalThresholdStop=3*this.rotateIntervalDuration_original;this.lastImgH=null;this.newImgV=this.lastImgV=this.newImgH=0;this.dx=this.settings.rotation.rotateDirection;!1==this.settings.rotation.rotateOnStart&&(this.dx=0);this.previousDx=
this.dx;this.dy=0},initCustomLogo:function(){var b,a,c;try{b=this.settings.custom.logo.imageUrl,a=this.settings.custom.logo.linkUrl,c=this.settings.custom.logo.linkTarget}catch(g){}"undefined"!==typeof b&&this.addCustomLogo(b,a,c)},addCustomLogo:function(b,a,c){var g,e;try{g=this.settings.custom.logo.imagePosition.left,e=this.settings.custom.logo.imagePosition.top}catch(f){e=g=5}var h=document.createElement("img");h.className="rotate-tool-custom-logo";h.style.zIndex=this.zIndex.customLogo;h.style.position=
"absolute";h.style.left=g+"px";h.style.top=e+"px";this.target.appendChild(h);g=this.path+b;0==b.indexOf("http")&&(g=b);h.src=g;a&&(c||(c="_blank"),RotateTool.addClickOrTouchListener(h,{forTouch:"touchend",forMouse:"click"},function(){return function(){window.open(a,c)}}()))},initHotspots:function(){var b=this.settings.hotspots;if(b){this.hotspotInstances={};for(var a in b)this.initHotspotInstance(b[a])}},initHotspotInstance:function(b){var a=document.createElement("div");a.initialized=!1;a.data=b;
a.style.display="none";a.style.position="absolute";a.style.cursor="pointer";a.style.zIndex=this.zIndex.hotspots;a.loaded=!1;a.id=b.id;b.icon=b.icon||{};if(b.icon.className)a.className=a.className+" "+b.icon.className;else if(b.icon.src){var c=document.createElement("img");c.src=this.path+b.icon.src;a.appendChild(c);a.image=c}else a.className+=" rotate-tool-hotspot-default";"undefined"!=typeof b.htmlContent?a.innerHTML=b.htmlContent:b.icon.src||(a.innerHTML='<div class="rotate-tool-hotspot-default-inner"></div>');
b.position&&(a.isFixed=!0,this.positionFixedHotspot(a));this.target.appendChild(a);this.addHotspotEvents(a,b);this.hotspotInstances[b.id]=a},positionFixedHotspot:function(b){var a=b.data;a.position.top&&(b.style.top=a.position.top+"px");a.position.left&&(b.style.left=a.position.left+"px");a.position.right&&(b.style.right=a.position.right+"px");a.position.bottom&&(b.style.bottom=a.position.bottom+"px")},addHotspotEvents:function(b,a){var c=this,g=b;b.image&&(g=b.image,g.data=b.data);RotateTool.addClickOrTouchListener(g,
RotateTool.eventsTouchStart,function(){c.hotspotTouchStartListener(a,b)});RotateTool.addClickOrTouchListener(g,RotateTool.eventsTouchEnd,function(){c.hotspotTouchEndListener(a,b)});RotateTool.addClickOrTouchListener(g,RotateTool.eventsMouseOver,RotateTool.bind(this,this.hotspotMouseOverListener));RotateTool.addClickOrTouchListener(g,RotateTool.eventsMouseOut,RotateTool.bind(this,this.hotspotMouseOutListener))},hotspotMouseOverListener:function(b){if(b&&b.target){var a=b.target.data;this.dispatchEvent(RotateTool.HOTSPOT_HOVER,
{originalEvent:b});a&&this.showToolTip(a,b.target)}},hotspotMouseOutListener:function(b){this.dispatchEvent(RotateTool.HOTSPOT_HOVER_OUT,{originalEvent:b});this.hideToolTipsInterval=setTimeout(RotateTool.bind(this,this.hideToolTips),250)},showToolTip:function(b,a,c){if(!b)return null;(b=this.getToolTip(b,a))&&b.show(c)},getToolTip:function(b,a){var c;this.tooltips[b.id]?c=this.tooltips[b.id]:(c=this.createToolTip(b,a),this.tooltips[b.id]=c);return c},hideToolTips:function(b){for(var a in this.tooltips)this.tooltips.hasOwnProperty(a)&&
this.tooltips[a].htmlElement&&"block"==this.tooltips[a].htmlElement.style.display&&b!=a&&!this.tooltips[a].timeoutToolTipOnHideCompleted&&!this.tooltips[a].keepVisible&&this.tooltips[a].hide()},createToolTip:function(b,a){if("object"!==typeof b.toolTip&&!b.title)return null;var c=this;return new function(b,e){this.htmlElement;this.positioning="CENTER_TO_HOTSPOT";this.keepVisible=this.timeoutToolTipOnHideCompleted=!1;this.createHtmlToolTip=function(){if(!b.toolTip.html.content)return null;this.htmlElement=
this.createToolTipWrapper();this.htmlElement.innerHTML=b.toolTip.html.content};this.createSimpleToolTip=function(){if(!b.title)return null;this.htmlElement=this.createToolTipWrapper();this.positioning="NEXT_TO_HOTSPOT";this.htmlElement.innerHTML='<span class="rotate-tool-tooltip">'+b.title.text.toString()+"</span>"};this.positionToolTip=function(){var c=10,h=10,l,m=this.htmlElement.offsetWidth,n=this.htmlElement.offsetHeight;if(!(m>=e.targetWidth||n>=e.targetHeight)){a instanceof Array&&2==a.length?
(c=a[0],h=a[1],l=20):("IMG"==a.tagName&&(a=a.parentNode),h=a.offsetTop,c=a.offsetLeft,l=a.offsetWidth);switch(this.positioning){case "CENTER_TO_HOTSPOT":c=Math.floor(c-0.5*m);h=Math.floor(h-0.5*n);break;default:c=c+l+5,"mousewheel_tooltip"==b.id&&(h+=10)}c=Math.max(c,10);h=Math.max(h,10);c=Math.min(c,e.targetWidth-m-10);h=Math.min(h,e.targetHeight-n-10)}this.htmlElement.style.left=c+"px";this.htmlElement.style.top=h+"px"};this.createToolTipWrapper=function(){var b=document.createElement("div");e.target.appendChild(b);
b.className="rotate-tool-tooltip-wrapper rotate-tool-unselectable";b.style.position="absolute";b.style.zIndex=RotateTool.zIndex.toolTip;b.style.display="none";b.style.opacity=0;b.style.cursor="pointer";RotateTool.addClickOrTouchListener(b,RotateTool.eventsTouchEnd,RotateTool.bind(this,this.mouseOrTouchEnd));RotateTool.addClickOrTouchListener(b,RotateTool.eventsMouseLeave,RotateTool.bind(this,this.mouseLeave));RotateTool.addClickOrTouchListener(b,RotateTool.eventsMouseOver,RotateTool.bind(this,this.mouseOver));
return b};this.mouseOrTouchEnd=function(){this.hide();RotateTool.isTouchDevice||(this.activeHotspot=null,e.executeHotspot(b))};this.mouseLeave=function(){this.hide();c.dispatchEvent(RotateTool.TOOLTIP_HOVER_OUT,{tooltipObject:this})};this.mouseOver=function(){clearTimeout(e.hideToolTipsInterval);c.dispatchEvent(RotateTool.TOOLTIP_HOVER,{tooltipObject:this})};this.show=function(a){this.htmlElement&&(e.hideToolTips(b.id),this.timeoutToolTipOnHideCompleted?(this.htmlElement.style.opacity=1,this.htmlElement.style.display=
"block",clearTimeout(this.timeoutToolTipOnHideCompleted),this.timeoutToolTipOnHideCompleted=null):(this.htmlElement.style.display="block",this.positionToolTip(),this.htmlElement.style.MozTransition="opacity 0.4s ease-in-out",this.htmlElement.style.WebkitTransition="opacity 0.4s ease-in-out",this.htmlElement.style.opacity=1,this.timeoutToolTipOnHideCompleted=null,c.dispatchEvent(RotateTool.TOOLTIP_SHOW,{hotspotData:b,tooltipElement:this.htmlElement}),a&&(a=parseInt(a),this.autoHideTimout=setTimeout(RotateTool.bind(this,
this.hide),a))))};this.hide=function(){this.htmlElement.style.MozTransition="opacity 0.3s ease-in-out";this.htmlElement.style.WebkitTransition="opacity 0.3s ease-in-out";this.htmlElement.style.opacity=0;this.timeoutToolTipOnHideCompleted=setTimeout(RotateTool.bind(this,this.onHideCompleted),300)};this.onHideCompleted=function(){this.htmlElement.style.display="none";this.timeoutToolTipOnHideCompleted=null};this.initialize=function(){!0==b.keepVisible&&(this.keepVisible=!0);b.toolTip&&typeof("object"==
b.toolTip.html)?this.createHtmlToolTip():b.title&&this.createSimpleToolTip()};this.initialize()}(b,this)},hotspotTouchStartListener:function(b,a){this.activeHotspot=b.id;RotateTool.isTouchDevice&&(this.executeHotspot(b,a),this.activeHotspot=null)},hotspotTouchEndListener:function(b,a){RotateTool.isTouchDevice||null===this.activeHotspot||this.activeHotspot!=b.id||(this.executeHotspot(b,a),this.activeHotspot=null)},executeHotspot:function(b,a){this.stopRotation();this.dispatchEvent(RotateTool.HOTSPOT_OPEN,
{hotspotData:b,hotspotElement:a});RotateTool.isObjectEmpty(b.image)?RotateTool.isObjectEmpty(b.javascript)?RotateTool.isObjectEmpty(b.url)?RotateTool.isObjectEmpty(a)||RotateTool.isTouchDevice&&this.showToolTip(b,a):this.executeUrlHotspot(b.url):this.executeJavascriptHotspot(b.javascript,a):this.executeImageHotspot(b.image)},executeJavascriptHotspot:function(b,a){var c=b.command,e=b.attribute,k={hotspotElement:a,instance:this};try{"function"==typeof window[c]&&window[c].call(window,e,k)}catch(f){RotateTool.reportUserError(f)}},
executeUrlHotspot:function(b){var a=b.src;b=b.target;a&&(b||(b="_top"),window.open(a,b))},executeImageHotspot:function(b){this.createImageHotspotOvelay();this.loadHotspotImage(b)},createImageHotspotOvelay:function(){var b=this.targetWidth,a=this.targetHeight,c=document.createElement("div");c.style.width=b+"px";c.style.height=a+"px";c.style.background="black";c.style.opacity="0.65";c.style.filter="alpha(Opacity=65)";c.style.display="block";c.style.position="absolute";c.style.left="0px";c.style.top=
"0px";c.style.cursor="pointer";c.style.zIndex=this.zIndex.overlay;this.target.appendChild(c);var e=document.createElement("div");e.innerHTML="Loading...";e.style.color="white";e.style.position="absolute";e.style.fontFamily="sans-serif";e.style.top=0.45*a+"px";e.style.left=0.5*b-30+"px";c.loading=e;c.appendChild(e);this.hotspotOverlay=c},loadHotspotImage:function(b){var a=document.createElement("img");a.data=b;a.onload=this.hotspotImageLoaded.apply(this,[a]);a.onerror=this.hotspotImageError.apply(this,
[a]);a.src=this.path+b.src},hotspotImageError:function(b){return function(){alert("Error loading image:"+b.src)}},hotspotImageLoaded:function(b){var a=this;return function(){a.target.appendChild(b);b.style.display="block";b.style.position="absolute";b.style.top="0px";b.style.left="0px";b.style.cursor="pointer";b.style.zIndex=a.zIndex.hotspotImage;this.relativeY=this.relativeX=0.5;a.fitHotspotImageToTarget(b);a.hotspotImage=b;b.data.title&&a.addHotspotTitle(b.data);RotateTool.addClickOrTouchListener(b,
RotateTool.eventsTouchEnd,RotateTool.bind(a,a.hideImageHotspot))}},fitHotspotImageToTarget:function(b){var a=1,c=b.width,a=b.height,a=this.targetRatio<c/a?this.targetWidth/c:this.targetHeight/a,c=Math.floor(b.height*a),a=Math.floor(b.width*a);b.height=c;b.width=a;b.width<this.targetWidth&&(b.style.left=Math.floor(0.5*(this.targetWidth-a))+"px",b.style.top="0px");b.height<this.targetHeight&&(b.style.top=Math.floor(0.5*(this.targetHeight-c))+"px",b.style.left="0px")},addHotspotTitle:function(b){var a=
document.createElement("div");a.className="rotate-tool-image-hotspot-title";a.innerHTML='<div class="rotate-tool-image-hotspot-title-inner">'+b.title+"</div";a.style.zIndex=this.zIndex.hotspotTitle;a.style.width=this.targetWidth+"px";2>this.settings.stylesVersion&&(a.style.position="absolute",a.style.left="0px",a.style.bottom="0px",a.style.fontFamily="sans-serif",a.style.color="white",a.style.backgroundColor="#000000",a.style.textAlign="left",a.style.padding="10px",a.style.opacity="0.75",a.style.fontSize=
"18px");this.hotspotTitle=a;this.target.appendChild(a)},hideImageHotspot:function(){this.target.removeChild(this.hotspotImage);this.target.removeChild(this.hotspotOverlay);this.target.removeChild(this.hotspotTitle);this.hotspotImage=null},redrawHotspots:function(){if(null!==this.hotspotInstances&&(this.hideAllHotspots(),this.currentImage&&!1!=this.isHotspotsVisible)){this.showFixedHotspots();var a=this.currentImage.hotspots;if(null!==a)for(var d=0;d<a.length;d++)this.showHotspot(a[d])}},hideAllHotspots:function(){for(var a in this.hotspotInstances)this.hotspotInstances[a].style.display=
"none"},showFixedHotspots:function(){var a,d,c;for(c in this.hotspotInstances)if(this.hotspotInstances[c].isFixed)if(a=this.hotspotInstances[c].data.levels)for(this.hotspotInstances[c].style.display="none",d=0;d<a.length;d++){if(a[d]==this.lastImgV){this.hotspotInstances[c].style.display="block";break}}else this.hotspotInstances[c].style.display="block"},showHotspot:function(a){var d=this.hotspotInstances[a.id];if(d&&!d.isFixed){d.style.display="block";var c,e;d.image?(c=d.image.width,e=d.image.height):
(c=d.offsetWidth,e=d.offsetHeight);d.isFixed||(c=this.currentImage.offsetLeft+a.rx*this.currentImage.width-0.5*c,d.style.top=Math.floor(this.currentImage.offsetTop+a.ry*this.currentImage.height-0.5*e)+"px",d.style.left=Math.floor(c)+"px")}},getWorkingDx:function(){return 0!=this.previousDx?this.previousDx:0>this.settings.rotation.rotateDirection?-1:1},startRotation:function(){this.dispatchEvent(RotateTool.ROTATION_START);0==this.dx&&(this.dx=this.getWorkingDx());this.isRotating=!0;this.rotateIntervalDuration_current=
this.rotateIntervalDuration_original},stopRotation:function(){0!=this.dx&&(this.dispatchEvent(RotateTool.ROTATION_STOP),this.isRotating=!1,this.previousDx=this.dx,this.dx=0,this.setScale(this.scaleInPercent,this.currentImage))},stopRotationSmooth:function(){this.dispatchEvent(RotateTool.ROTATION_STOP);this.durationMultiplier=1.05},startRotationSmooth:function(){this.dispatchEvent(RotateTool.ROTATION_START);this.dx=this.getWorkingDx();this.rotateIntervalDuration_current=1.5*this.rotateIntervalDuration_original;
this.durationMultiplier=0.95},rotateLoop:function(){1!=this.durationMultiplier&&(this.rotateIntervalDuration_current*=this.durationMultiplier,this.rotateIntervalDuration_current>this.rotateIntervalDuration_original&&(this.rotateIntervalDuration_current=this.rotateIntervalDuration_original,this.durationMultiplier=1));window.requestAnimationFrame&&window.requestAnimationFrame(RotateTool.bind(this,this.rotateLoop));this.okNextImage()&&this.showNextImage()},showNextImage:function(a){null==this.lastImgH?
this.newImgV=this.newImgH=0:(this.newImgH=this.lastImgH+this.dx,this.newImgV=this.lastImgV+this.dy);this.newImgH>=this.hSteps&&(this.newImgH=0,this.bounce&&(this.newImgH=this.hSteps-1,this.dx=-this.dx));0>this.newImgH&&(this.newImgH=this.hSteps-1,this.bounce&&(this.newImgH=0,this.dx=-this.dx));this.newImgV>=this.vSteps&&(this.newImgV=this.vSteps-1);0>this.newImgV&&(this.newImgV=0);this.currentImage=this.rotateImages[this.imagesGrid[this.newImgV][this.newImgH]];if(!this.previousImage||this.previousImage!=
this.currentImage){this.requestRescaleFlag&&this.setRescaleFlag();var d={imgH:this.newImgH,imgV:this.newImgV,imgSrc:this.currentImage.src,imageId:this.currentImage.idNumber,fileName:this.currentImage.fileName};!1===("undefined"===typeof a?!1:a)&&this.dispatchEvent(RotateTool.ON_IMAGE,d);this.setScale(this.scaleInPercent,this.currentImage);this.previousImage&&(this.previousImage.style.visibility="hidden");this.currentImage&&(this.currentImage.style.visibility="visible");this.hideToolTips();this.previousImage=
this.currentImage;this.redrawHotspots();this.lastImgH=this.newImgH;this.lastImgV=this.newImgV;this.settings.rotation.rotateOnce&&(this.rotateOnceCounter++,this.rotateOnceCounter==this.hSteps+1&&this.stopRotation());this.timeLastImageShown=Date.now();this.currentImage.width>this.currentImage.normalImageWidth&&this.currentImage.srcLarge&&this.loadNextLargeImage(this.currentImage)}},okNextImage:function(){var a=Date.now()-this.timeLastImageShown;if(!this.previousImage)return!0;if(0==this.dx&&0==this.dy)return!1;
if(a>this.rotateIntervalDuration_current)return!0},setScale:function(a,d){if(d&&!d.scaled){a=Math.max(100,a);this.scaleInPercent=a=Math.min(a,this.settings.control.maxZoom);var c=1,e=!0,c=this.targetRatio<d.ratio?this.targetWidth/d.originalWidth:this.targetHeight/d.originalHeight,c=c*(a/100);this.settings.control.maxZoomAuto&&100<a&&d.src==d.srcLarge&&1<c&&(c=1);var k;k=Math.floor(d.originalHeight*c);c=Math.floor(d.originalWidth*c);d.style.width=c+"px";d.style.height=k+"px";this.objectWidth=Math.floor(0.9*
c);this.objectHeight=Math.floor(0.8*k);if(100<a){c=-this.relativeX*c+0.5*this.targetWidth;k=-this.relativeY*k+0.5*this.targetHeight;var f=parseInt(this.currentImage.style.width),h=parseInt(this.currentImage.style.height),l=this.targetWidth-f-0,m=this.targetHeight-h-0;f>this.targetWidth&&(c=Math.min(c,0),c=Math.max(c,l));h>this.targetHeight&&(k=Math.min(k,0),k=Math.max(k,m));d.style.top=""+k+"px";d.style.left=""+c+"px"}else this.relativeY=this.relativeX=0.5,c<this.targetWidth&&k<this.targetHeight&&
(d.style.top=Math.floor(0.5*(this.targetHeight-k))+"px",d.style.left=Math.floor(0.5*(this.targetWidth-c))+"px"),c==this.targetWidth&&k==this.targetHeight&&(d.style.left="0px",d.style.top="0px"),c<this.targetWidth&&k==this.targetHeight&&(d.style.left=Math.floor(0.5*(this.targetWidth-c))+"px",d.style.top="0px"),c==this.targetWidth&&k<this.targetHeight&&(d.style.top=Math.floor(0.5*(this.targetHeight-k))+"px",d.style.left="0px");c=!1;d.width>d.normalImageWidth&&d.srcLarge&&(c=!0);100<a||c&&!0==this.isImagesLoaded?
d.srcLarge&&d.src!=d.srcLarge&&(d.largeImageWidth?(d.originalWidth=d.largeImageWidth,d.originalHeight=d.largeImageHeight,d.scaled=!1,d.src=d.srcLarge):this.isSpinning()?e=!1:this.loadLargeImage(d,!0)):d.src==d.srcLarge&&(d.src=d.srcNormal);d.scaled=e;d.correctLeft=d.style.left;this.redrawHotspots()}},setRescaleFlag:function(){for(var a=0;a<this.rotateImages.length;a++)this.rotateImages[a].scaled=!1;this.requestRescaleFlag=!1},addControls:function(){this.settings.userInterface.showTogglePlayButton&&
this.addPlayPauseButton();this.settings.userInterface.showZoomSlider&&this.addZoomSlider();this.settings.userInterface.showArrows&&this.addArrowButtons();this.settings.userInterface.showZoomButtons&&this.addZoomButtons();this.settings.userInterface.showToggleFullscreenButton&&RotateTool.isFullscreenBrowserAPISupported&&this.addFullscreenButton();RotateTool.yofla_360_is_preview&&this.settings.userInterface.showToggleFullscreenButton&&this.addFullscreenButton();if("true"==this.settings.userInterface.showToggleRotateButton||
!0==this.settings.userInterface.showToggleRotateButton||"zoom"==this.settings.userInterface.showToggleRotateButton)this.addToggleRotateButton(),this.addTogglePanButton(),this.toggleRotationInZoomMode(!1),"zoom"==this.settings.userInterface.showToggleRotateButton?this.toggleToggleRotatePanButtons(!1):this.toggleToggleRotatePanButtons(!0);this.settings.control.disableMouseControl||(this.addClickPane(),this.addClickPaneTouchControls())},addPlayPauseButton:function(){return this.generateButton("rotate-tool-button-play",
this.playButtonClickListener)},playButtonClickListener:function(a){this.dispatchEvent(RotateTool.BUTTON_PLAY_PAUSE_CLICK);this.toggleRotation();RotateTool.pauseEvent(a)},addToggleRotateButton:function(){return this.generateButton("rotate-tool-button-toggle-rotate",this.toggleRotateButtonClickListener)},toggleRotateButtonClickListener:function(a){a.stopPropagation();this.dispatchEvent(RotateTool.BUTTON_ROTATE_CLICK);this.toggleRotationInZoomMode(!0)},addTogglePanButton:function(){return this.generateButton("rotate-tool-button-toggle-pan",
this.togglePanButtonClickListener)},togglePanButtonClickListener:function(a){a.stopPropagation();this.dispatchEvent(RotateTool.BUTTON_PAN_CLICK);this.toggleRotationInZoomMode(!1)},toggleRotationInZoomMode:function(a){var d=this.buttons["rotate-tool-button-toggle-pan"],c=this.buttons["rotate-tool-button-toggle-rotate"],e;c&&(e=(e=this.buttons["rotate-tool-button-toggle-rotate"].offsetWidth)?e:22);a?(this.isRotationWhenZoomed=!0,this.dispatchEvent(RotateTool.TOGGLE_ROTATE_MODE),d&&(d.style.backgroundPosition=
"0px"),c&&(c.style.backgroundPosition="-"+e+"px")):(this.isRotationWhenZoomed=!1,this.dispatchEvent(RotateTool.TOGGLE_PAN_MODE),d&&(d.style.backgroundPosition="-"+e+"px"),c&&(c.style.backgroundPosition="0px"))},addFullscreenButton:function(){return this.generateButton("rotate-tool-button-fullscreen",this.fullscreenButtonClickListener)},fullscreenButtonClickListener:function(a){a.stopPropagation();a=this.target;this.dispatchEvent(RotateTool.BUTTON_FULLSCREEN_CLICK);RotateTool.yofla_360_is_preview?
alert("Please preview fullscreen in a browser (requires iframe embed)."):(this.requestRescaleFlag=!0,this.isZoomed&&this.resetZoom(),RotateTool.isFullscreen()?(RotateTool.exitFullscreen(a),this.target.className=this.targetClassNameBeforeFullscreen):(RotateTool.launchFullscreen(a),this.targetClassNameBeforeFullscreen=this.target.className,this.target.className+=" in-fullscreen"))},addArrowButtons:function(){this.generateButton("rotate-tool-button-left",this.leftButtonClickListener);this.generateButton("rotate-tool-button-right",
this.rightButtonClickListener);1<this.vSteps&&(this.generateButton("rotate-tool-button-up",this.upButtonClickListener),this.generateButton("rotate-tool-button-down",this.downButtonClickListener))},addZoomButtons:function(){this.generateButton("rotate-tool-button-zoom-in",this.zoomInButtonClickListener);this.generateButton("rotate-tool-button-zoom-out",this.zoomOutButtonClickListener)},leftButtonClickListener:function(a){this.dispatchEvent(RotateTool.BUTTON_ARROW_LEFT_CLICK);a.stopPropagation();this.stopRotation();
this.dx=1;this.dy=0;this.settings.control.reverseDrag&&(this.dx=-this.dx);this.previousDx=this.dx;this.showNextImage();this.dx=0},rightButtonClickListener:function(a){this.dispatchEvent(RotateTool.BUTTON_ARROW_RIGHT_CLICK);a.stopPropagation();this.stopRotation();this.dx=-1;this.dy=0;this.settings.control.reverseDrag&&(this.dx=-this.dx);this.previousDx=this.dx;this.showNextImage();this.dx=0},upButtonClickListener:function(a){a.stopPropagation();this.resetZoom();this.stopRotation();this.dx=0;this.dy=
1;this.showNextImage();this.dy=0},downButtonClickListener:function(a){a.stopPropagation();this.resetZoom();this.stopRotation();this.dx=0;this.dy=-1;this.showNextImage();this.dy=0},zoomInButtonClickListener:function(a){this.dispatchEvent(RotateTool.BUTTON_ZOOM_IN_CLICK);a.stopPropagation();this.zoomStepHandler("zoomIn")},zoomOutButtonClickListener:function(a){this.dispatchEvent(RotateTool.BUTTON_ZOOM_OUT_CLICK);a.stopPropagation();this.zoomStepHandler("zoomOut")},zoomStepHandler:function(a){var d=
this.settings.control.maxZoom,c;"zoomIn"===a?(c=this.currentZoomValue+this.zoomStepInRatio,c=Math.min(c,d/100)):(c=this.currentZoomValue-this.zoomStepInRatio,c=Math.max(c,0));var e=this.currentZoomValue,k=0,f;clearInterval(this.zoomInterval);this.zoomInterval=setInterval(RotateTool.bind(this,function(){k++;21<=k?(clearInterval(this.zoomInterval),this.zoomRatioChangeListener(c,"zoomButton")):(f=RotateTool.Quad_easeOut(k,e,c-e,21),this.zoomRatioChangeListener(f,"zoomButton"))}),700/30)},generateButton:function(a,
d){var c=document.createElement("div");c.className="rotate-tool-button "+a;c.style.zIndex=this.zIndex.buttons;c.style.position="absolute";this.target.appendChild(c);RotateTool.addClickOrTouchListener(c,{forTouch:"touchend",forMouse:"click"},RotateTool.bind(this,d));return this.buttons[a]=c},addZoomSlider:function(){var a=this,d=this.createSliderContainer(),c=this.createSliderHandle(),e=97,k=function(d){d||(d=window.event);var e=RotateTool.getMousePosition(d).x-c.mouseStartX,e=c.currentX+e,e=Math.max(0,
e),e=Math.min(a.handleMaxX,e);isNaN(e)&&(e=0);c.style.left=e+"px";a.zoomRatioChangeListener(e/a.handleMaxX,"sliderHandle");RotateTool.isTouchDevice&&d.preventDefault();RotateTool.pauseEvent(d)},f=function(d){d||(d=window.event);c.currentX=c.newOffsetX;RotateTool.removeClickOrTouchListener(document,RotateTool.eventsTouchMove,k);RotateTool.removeClickOrTouchListener(document,RotateTool.eventsTouchEnd,f);a.draggedObject=null;RotateTool.isTouchDevice&&d.preventDefault();RotateTool.pauseEvent(d)};RotateTool.addClickOrTouchListener(c,
RotateTool.eventsTouchStart,function(h){h.stopPropagation();e=d.offsetWidth-c.offsetWidth;a.handleMaxX=e;h||(h=window.event);a.draggedObject=c;a.dispatchEvent(RotateTool.BUTTON_ZOOMSLIDER_CLICK);c.mouseStartX=RotateTool.getMousePosition(h).x;c.currentX=parseInt(c.style.left);isNaN(c.currentX)&&(c.currentX=0);RotateTool.addClickOrTouchListener(document,RotateTool.eventsTouchMove,k);RotateTool.addClickOrTouchListener(document,RotateTool.eventsTouchEnd,f);RotateTool.isTouchDevice&&h.preventDefault();
RotateTool.pauseEvent(h)});d.appendChild(c);this.target.appendChild(d);this.sliderHandle=c;this.handleMaxX=e},createSliderContainer:function(){var a=document.createElement("div");a.className="rotate-tool-zoomslider rotate-tool-unselectable";a.style.zIndex=this.zIndex.buttons;a.style.position="absolute";return a},createSliderHandle:function(){var a=document.createElement("div");a.className="rotate-tool-zoomslider-handle rotate-tool-unselectable";a.style.position="absolute";a.currentX=0;return a},updateSliderHandlePosition:function(a){this.sliderHandle&&
(this.sliderHandle.style.left=Math.floor(a*this.handleMaxX)+"px")},addClickPane:function(){var a=document.createElement("div");a.style.width="100%";a.style.height="100%";a.style.background="white";a.style.opacity="0";a.style.filter="alpha(Opacity=0)";a.style.display="block";a.style.position="absolute";a.style.left="0px";a.style.top="0px";a.style.cursor="pointer";a.style.zIndex=this.zIndex.clickPane;this.target.appendChild(a);this.clickPane=a},addClickPaneTouchControls:function(){RotateTool.addClickOrTouchListener(this.clickPane,
RotateTool.eventsTouchMove,RotateTool.bind(this,this.clickPaneMouseOrTouchMove));RotateTool.addClickOrTouchListener(this.clickPane,RotateTool.eventsTouchStart,RotateTool.bind(this,this.clickPaneMouseOrTouchStart));RotateTool.addClickOrTouchListener(this.clickPane,RotateTool.eventsTouchEnd,RotateTool.bind(this,this.clickPaneMouseOrTouchEnd));RotateTool.addClickOrTouchListener(document,RotateTool.eventsTouchEnd,RotateTool.bind(this,this.clickPaneMouseOrTouchEnd));this.settings.control.rotateOnMouseHover&&
!RotateTool.isTouchDevice&&this.addRotateOnHoverActions();!1==RotateTool.isTouchDevice&&(this.clickPane.addEventListener?(this.clickPane.addEventListener("mousewheel",RotateTool.bind(this,this.MouseWheelHandler),!1),this.clickPane.addEventListener("DOMMouseScroll",RotateTool.bind(this,this.MouseWheelHandler),!1)):this.clickPane.attachEvent("onmousewheel",RotateTool.bind(this,this.MouseWheelHandler)))},clickPaneMouseOrTouchStart:function(a){a=a||window.event;this.hideContexMenu();this.hideToolTips();
this.wasRotating=0!=this.dx;this.stopRotation();if(a.button&&2==a.button)return a.preventDefault&&a.preventDefault(),!1;this.isTouchOrMouseDown=!0;this.touchMovePreviousDrag=this.touchMovePrevious=this.touchMove=this.touchStart=RotateTool.getMousePosition(a);this.isMouseMoved=!1;this.windowYPositionAtTouchStart=(window.pageYOffset||document.documentElement.scrollTop)-(document.documentElement.clientTop||0);this.windowXPositionAtTouchStart=(window.pageXOffset||document.documentElement.scrollLeft)-
(document.documentElement.clientLeft||0);if(RotateTool.isRunningInIframe)try{this.windowYPositionAtTouchStart=(window.parent.pageYOffset||window.parent.document.documentElement.scrollTop)-(window.parent.document.documentElement.clientTop||0),this.windowXPositionAtTouchStart=(window.parent.pageXOffset||window.parent.document.documentElement.scrollLeft)-(window.parent.document.documentElement.clientLeft||0)}catch(d){}this.touchStart.lastImgH=this.lastImgH;this.touchStart.lastImgV=this.lastImgV;this.currentImage.startOffsetX=
parseInt(this.currentImage.style.left,10);this.currentImage.startOffsetY=parseInt(this.currentImage.style.top,10);this.isZoomed?this.isRotationWhenZoomed?this.dispatchEvent(RotateTool.TURN_START,this.lastImgH):this.dispatchEvent(RotateTool.PAN_START,this.lastImgH):this.dispatchEvent(RotateTool.TURN_START,this.lastImgH);RotateTool.isTouchDevice&&a.touches&&2==a.touches.length&&(this.isGestureStart=!0);RotateTool.isTouchDevice&&a.preventDefault()},clickPaneMouseOrTouchMove:function(a){this.isTouchOrMouseDown&&
(this.touchMove=RotateTool.getMousePosition(a),RotateTool.isTouchDevice&&a.preventDefault(),this.isGestureStart?this.handleMultiTouchGesture(a):(this.isZoomed&&this.isTouchOrMouseDown&&this.evalClickPaneTouchMove(this.touchStart,this.touchMove),this.isDragging||this.startDragListener(this.touchMove),this.isDragging&&this.dragListener(a)),this.touchMovePrevious=this.touchMove)},clickPaneMouseOrTouchEnd:function(a){this.isGestureStart=!1;this.gestureStartValue=null;if(!0==this.isTouchOrMouseDown){this.isTouchOrMouseDown=
!1;this.touchEnd=RotateTool.getMousePosition(a);var d=this.evalClickPaneTouchEnd(this.touchStart,this.touchEnd);this.isDragging&&this.stopDragListener(a);!1==d?100==this.scaleInPercent?this.dispatchEvent(RotateTool.TURN_STOP,this.lastImgH):this.isRotationWhenZoomed?this.dispatchEvent(RotateTool.TURN_STOP,this.lastImgH):this.dispatchEvent(RotateTool.PAN_STOP,this.lastImgH):this.evalClickOnPane(this.touchEnd);this.settings.control.rotateOnMouseHover&&!1==RotateTool.isTouchDevice&&this.clickPaneMouseOrTouchStart(a)}},
handleMultiTouchGesture:function(a){if(a.touches)if(a=a.touches.item(1).clientX-a.touches.item(0).clientX,0>a&&(a=-a),null===this.gestureStartValue)this.gestureStartValue=a;else{var d=0.01,d=-1.33334E-4*(this.settings.control.maxZoom-100)+0.0566667,d=Math.max(d,0.01);a<this.gestureStartValue&&(d=-d);this.zoomRatioChangeListener(this.currentZoomValue+d,"pinchGesture")}},addRotateOnHoverActions:function(){this.clickPane.addEventListener("mouseenter",RotateTool.bind(this,this.clickPaneMouseOver),!0);
this.clickPane.addEventListener("mouseleave",RotateTool.bind(this,this.clickPaneMouseOut),!0)},clickPaneMouseOver:function(a){this.clickPaneMouseOrTouchStart(a)},clickPaneMouseOut:function(a){this.clickPaneMouseOrTouchEnd(a)},clickPaneMouseMove:function(a){},startDragListener:function(a){this.isZoomed&&!1==this.isRotationWhenZoomed||(this.lastYatDyChange=a.y,this.rotateIntervalDuration_current=this.rotateIntervalDuration_original*this.settings.control.dragSpeed,this.isDragging=!0,this.touchMovePreviousDrag=
this.touchStart,this.dx=0)},stopDragListener:function(a){this.isDragging=!1;this.dy=0;this.dx=this.getWorkingDx();this.rotateIntervalDuration_current<0.5*this.rotateIntervalDuration_original&&(this.durationMultiplier=1.015);if(a.timeStamp-this.touchMove.timeStamp>this.THRESHOLD_TIME_DRAG_STOP_ROTATE||!1==this.settings.control.enableSwing)this.dy=this.dx=0,this.rotateIntervalDuration_current=this.rotateIntervalDuration_original},dragListener:function(a){var d=a=0,c=0.5;this.bounce&&(c=1);if(!this.isGestureStart&&
this.touchStart&&this.touchMove){a=this.touchStart.y-this.touchMove.y;d=this.touchStart.x-this.touchMove.x;this.previousDx=RotateTool.signum(this.touchMovePreviousDrag.x-this.touchMove.x);0==this.previousDx&&(this.previousDx=RotateTool.signum(d));this.settings.control.reverseDrag&&(d*=-1,this.previousDx*=-1);c=Math.floor(this.hSteps*(d/this.objectWidth)*c);c=0<=c?c%this.hSteps:-(Math.abs(c)%this.hSteps);c=this.touchStart.lastImgH+c;0>c?(c+=this.hSteps,this.bounce&&(c=0)):c>=this.hSteps&&(c%=this.hSteps,
this.bounce&&(c=this.hSteps-1));var e=this.touchStart.lastImgV+Math.floor(this.vSteps*(a/this.objectHeight));0>e&&(e=0);e>=this.vSteps&&(e=this.vSteps-1);if(1==this.vSteps&&25>Math.abs(d)&&100==this.scaleInPercent&&!0==this.settings.control.touchPageScroll&&!0==RotateTool.isTouchDevice){d=window;RotateTool.isRunningInIframe&&(d=window.parent);try{d.scrollTo(this.windowXPositionAtTouchStart,this.windowYPositionAtTouchStart+a)}catch(k){}}this.dy=this.dx=0;this.lastImgH=c;this.lastImgV=e;a=this.timeLastImageShown;
this.showNextImage();this.rotateIntervalDuration_current=Date.now()-a;this.touchMovePreviousDrag=this.touchMove}},evalClickPaneTouchEnd:function(a,d){var c=!1,e=1;if(d&&a){var k=Math.abs(d.x-a.x),f=Math.abs(d.y-a.y);RotateTool.isTouchDevice&&(e=8);k+f<=e&&(c=!0);return c}},evalClickPaneTouchMove:function(a,d){var c=d.x-a.x,e=d.y-a.y,k=!1;if(!(RotateTool.isTouchDevice&&10>=Math.abs(c)+Math.abs(e))){Math.abs(e)>Math.abs(c)&&1==this.vSteps&&(k=!0);var f=d.timeStamp-a.timeStamp;!1==this.isMouseMoved&&
(f>this.THRESHOLD_TIME_ROTATE_PAN_DIF||k?this.toggleRotationInZoomMode(!1):this.toggleRotationInZoomMode(!0));if(!this.isRotationWhenZoomed){var c=this.currentImage.startOffsetX+c,e=this.currentImage.startOffsetY+e,k=parseInt(this.currentImage.style.width),f=parseInt(this.currentImage.style.height),h=this.targetWidth-k-0,l=this.targetHeight-f-0;k>this.targetWidth&&(c=Math.min(c,0),c=Math.max(c,h));f>this.targetHeight&&(e=Math.min(e,0),e=Math.max(e,l));c>0.5*this.targetWidth&&(c=Math.floor(0.5*this.targetWidth));
e>0.5*this.targetHeight&&(e=Math.floor(0.5*this.targetHeight));c+k<0.5*this.targetWidth&&(c=Math.floor(0.5*this.targetWidth)-k);e+f<0.5*this.targetHeight&&(e=Math.floor(0.5*this.targetHeight)-f);if(this.currentImage)try{this.currentImage.style.left=c+"px",this.currentImage.style.top=e+"px",this.relativeX=-(c-0.5*this.targetWidth)/parseInt(k),this.relativeY=-(e-0.5*this.targetHeight)/parseInt(f)}catch(m){}this.setRescaleFlag()}this.redrawHotspots();this.isMouseMoved=!0}},evalClickOnPane:function(a){this.dispatchEvent(RotateTool.CLICK_OBJECT);
this.settings.control.clickUrl?(this.stopRotation(),this.openClickUrl()):(this.dx=this.wasRotating?this.getWorkingDx():0,this.checkDoubleClick(a)&&100!=this.scaleInPercent&&this.resetZoom(),this.toggleRotation())},checkDoubleClick:function(a){var d=a.timeStamp;if(this.previousTouchEndTime&&(a=d-this.previousTouchEndTime,300>a))return!0;this.previousTouchEndTime=d;return!1},openClickUrl:function(){var a=this.settings.control.clickUrl,d=this.settings.control.clickUrlTarget;a&&(d||(d="_top"),window.open(a,
d))},MouseWheelHandler:function(a){a=window.event||a;var d=Math.max(-1,Math.min(1,a.wheelDelta||-a.detail));try{a.preventDefault()}catch(c){}this.settings.control.mouseWheelZooms||a.ctrlKey||a.metaKey?(a=this.settings.control.maxZoom,this.stopRotation(),this.zoomRatioChangeListener(1/(a-100)*(this.scaleInPercent-10*d)-100*(1/(a-100)),"mouseWheel")):(!0!==this.toolTipOnMouseWheelShown&&!1==RotateTool.isTouchDevice&&(a=RotateTool.getLocalMousePosition(a),this.showToolTip({id:"mousewheel_tooltip",keepVisible:!0,
title:{text:"Tip: use MouseWheel+Ctrl for Zooming"}},[a.x,a.y],3E3),this.toolTipOnMouseWheelShown=!0),this.stopRotation(),this.dx=d,this.mouseWheelCounter++,0==this.mouseWheelCounter%4&&this.showNextImage())},toggleRotation:function(){0==this.dx?this.startRotation():this.stopRotation()},windowResizeListener:function(a){this.wasRotating=0!=this.dx;this.stopRotation();this.resetZoom();this.updateTargetStyles();this.updateMaxZoom();this.currentImage&&(this.currentImage.scaled=!1);this.setScale(100,this.currentImage);
this.requestRescaleFlag=!0;this.wasRotating&&(this.dx=this.getWorkingDx(),this.startRotation())},fullscrentChangedListener:function(){RotateTool.isFullscreen();this.windowResizeListener()},zoomRatioChangeListener:function(a,d){this.stopRotation();a=Math.max(0,a);this.currentZoomValue=a=Math.min(1,a);var c=100+(this.settings.control.maxZoom-100)*a;this.dispatchEvent(RotateTool.ZOOM_CHANGE,this.lastImgH);0==a&&this.dispatchEvent(RotateTool.ZOOM_RESET,this.lastImgH);this.currentImage&&(this.currentImage.scaled=
!1,this.setScale(c,this.currentImage),this.currentImage.scaled=!1);this.requestRescaleFlag=!0;this.isZoomed=0!==a;"sliderHandle"!=d&&this.updateSliderHandlePosition(a);"zoom"==this.settings.userInterface.showToggleRotateButton&&this.toggleToggleRotatePanButtons(0!=a)},toggleToggleRotatePanButtons:function(a){this.buttons["rotate-tool-button-toggle-pan"]&&this.buttons["rotate-tool-button-toggle-rotate"]&&(a?(this.buttons["rotate-tool-button-toggle-pan"].style.display="block",this.buttons["rotate-tool-button-toggle-rotate"].style.display=
"block"):(this.buttons["rotate-tool-button-toggle-pan"].style.display="none",this.buttons["rotate-tool-button-toggle-rotate"].style.display="none"))},resetZoom:function(){this.zoomRatioChangeListener(0,null);this.requestRescaleFlag=!0},reportBrowserNotSupported:function(){this.target.innerHTML='<span class="rotate-tool-browser-not-supported">Your browser does not support this 3D Object rotation script.</span>'},addPlayerInfo:function(){var a=document.createElement("div"),d=document.createElement("a");
d.href="http://www.yofla.com/3d-rotate/player-about/";d.target="_blank";d.innerHTML="360 by YoFLA";d.style.textDecoration="none";d.style.color="navy";d.style.fontFamily="sans-serif";d.style.fontSize="10px";d.style.paddingLeft="5px";d.style.paddingRight="5px";a.appendChild(d);this.target.appendChild(a);a.style.position="absolute";a.style.top="2px";a.style.right="4px";a.style.zIndex=this.zIndex.info+1;a.style.background="white";a.style.borderRadius="5px";a.style.opacity=0.75;a.style.filter="alpha(Opacity=75)";
setTimeout(function(){a.style.display="none"},5500)},addEventListener:function(a,d,c){c="undefined"===typeof c?!1:c;!1===RotateTool.isCustomEventSupported?document.addEventListener(a,d,c):this.target.addEventListener(a,d,c)},removeEventListener:function(a,d,c){c="undefined"===typeof c?!1:c;!1===RotateTool.isCustomEventSupported?document.removeEventListener(a,d,c):this.target.removeEventListener(a,d,c)},dispatchEvent:function(a,d){this.detectZoomStart(a);this.isGAenabled&&this.reportGAevent(a,d);if(!1===
RotateTool.isCustomEventSupported)try{var c=document.createEvent("Event");c.initEvent(a,!0,!0);c.detail=d;document.dispatchEvent(c)}catch(e){}else c=new CustomEvent(a,{detail:d}),c.bubbles=!0,this.target.dispatchEvent(c)},detectZoomStart:function(a){a==RotateTool.ZOOM_CHANGE&&this.lastEventName!=RotateTool.ZOOM_CHANGE&&this.dispatchEvent(RotateTool.ZOOM_START);this.lastEventName=a},reportGAevent:function(a,d){if(!1!=RotateTool.isGAloaded(this.gaTrackingId)&&0<=this.gaEnabledEvents.indexOf(a)){var c=
this.gaCategory,e=this.gaLabel;!0==isNaN(d)?ga("send","event",c,a,e):ga("send","event",c,a,e,parseInt(d))}},rotateToolInstanceLast:"no colon"};e.initialize();return e},fixPathVariable:function(a){if(a&&0<a.length){var e=a.substr(a.length-1);"/"!=e&&"\\"!=e&&(a+="/")}else a="";return a},loadScript:function(a,e,b){var d=document.getElementsByTagName("head")[0],c=document.createElement("script");c.type="text/javascript";c.onreadystatechange=function(){if("loaded"===c.readyState||"complete"===c.readyState)c.onreadystatechange=
null,e.apply(b)};c.onload=function(){e.apply(b)};c.src=a;d.appendChild(c)},loadXMLFile:function(a,e,b){b.isXMLLoaded=!1;(new RotateTool.XMLloader).loadXML(a,e,!0,b)},parseJSON:function(a){if("string"!==typeof a||!a)return null;if(window.JSON&&window.JSON.parse)return window.JSON.parse(a);if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return(new Function("return "+
a))();throw"Invalid JSON: "+a;},addEventSimple:function(a,e,b){a.addEventListener?a.addEventListener(e,b,!1):a.attachEvent&&a.attachEvent("on"+e,b)},removeEventSimple:function(a,e,b){a.removeEventListener?a.removeEventListener(e,b,!1):a.detachEvent&&a.detachEvent("on"+e,b)},getMousePosition:function(a){if("undefined"===typeof a)return null;var e={x:null,y:null};a.changedTouches?(e.x=a.changedTouches[0].screenX,e.y=a.changedTouches[0].screenY):(e.x=a.clientX,e.y=a.clientY);e.timeStamp=a.timeStamp;
return e},getLocalMousePosition:function(a){a=a||window.event;var e=a.target||a.srcElement;e.currentStyle||window.getComputedStyle(e,null);e=e.getBoundingClientRect();return{x:a.clientX-e.left,y:a.clientY-e.top}},defaultPreloader:function(a,e){var b=this,d=e.color1,c=e.background.alpha,g=Math.floor(100*c),k={percentDiv:null,targetDiv:null,initialize:function(a){this.targetDiv=document.getElementById(a);this.backgroundDiv=document.createElement("div");this.backgroundDiv.style.left="0px";this.backgroundDiv.style.zIndex=
b.zIndex.preloader;this.backgroundDiv.style.position="absolute";this.backgroundDiv.style.top=Math.round(this.targetDiv.offsetHeight/2)-40+"px";this.backgroundDiv.style.width="100%";this.backgroundDiv.style.height="50px";e.background.enabled&&(this.backgroundDiv.style.backgroundColor=e.background.color,this.backgroundDiv.style.opacity=c,this.backgroundDiv.style.filter="alpha(Opacity="+g+")");this.targetDiv.appendChild(this.backgroundDiv);this.progressBar=document.createElement("div");this.progressBar.style.left=
"0px";this.progressBar.style.zIndex=b.zIndex.preloader;this.progressBar.style.position="absolute";this.progressBar.style.top=Math.round(this.targetDiv.offsetHeight/2)-40+"px";this.progressBar.style.width="0%";this.progressBar.style.height="50px";this.progressBar.style.backgroundColor="#909090";this.progressBar.style.opacity=0.5;this.progressBar.style.filter="alpha(Opacity=50)";this.targetDiv.appendChild(this.progressBar);this.percentDiv=document.createElement("div");this.percentDiv.style.fontSize=
"32px";this.percentDiv.style.fontFamily="verdana, arial, sans-serif";this.percentDiv.style.lineHeight="50px";this.percentDiv.style.textAlign="center";this.percentDiv.style.width="100%";this.percentDiv.style.top=Math.round(this.targetDiv.offsetHeight/2)-40+"px";this.percentDiv.style.zIndex=b.zIndex.preloader+1;this.percentDiv.style.position="absolute";this.percentDiv.style.color=d;this.percentDiv.style.opacity=1;this.percentDiv.style.filter="alpha(Opacity=100)";this.percentDiv.innerHTML="&nbsp; 0%";
this.percentDiv.setAttribute("id","preloader_"+this.targetDiv.id);this.targetDiv.appendChild(this.percentDiv)},update:function(a){var b="";10>a&&(b="&nbsp; ");this.percentDiv&&(this.percentDiv.innerHTML=b+a+"%");this.progressBar&&(this.progressBar.style.width=a+"%")},destroy:function(){this.percentDiv.innerHTML="";this.percentDiv.style.display="none";this.targetDiv.removeChild(this.percentDiv);this.targetDiv.removeChild(this.backgroundDiv);this.targetDiv.removeChild(this.progressBar);this.targetDiv=
this.percentDiv=this.progressBar=this.backgroundDiv=null}};k.initialize(a);return k},wavePreloader:function(a,e){var b=this,d=Number(e.background.alpha),c=Math.floor(100*d),g={percentDiv:null,targetDiv:null,initialize:function(a,f){this.targetDiv=document.getElementById(a);this.backgroundDiv=document.createElement("div");this.backgroundDiv.style.left="0px";this.backgroundDiv.style.zIndex=b.zIndex.preloader;this.backgroundDiv.style.position="absolute";this.backgroundDiv.style.top=Math.round(this.targetDiv.offsetHeight/
2)-33+"px";this.backgroundDiv.style.width="100%";this.backgroundDiv.style.height="50px";e.background.enabled&&(this.backgroundDiv.style.backgroundColor=e.background.color,this.backgroundDiv.style.opacity=d,this.backgroundDiv.style.filter="alpha(Opacity="+c+")");this.targetDiv.appendChild(this.backgroundDiv);this.percentDiv=document.createElement("div");this.percentDiv.style.zIndex=b.zIndex.preloader+1;this.percentDiv.style.position="relative";var h;h=""+('<div class="yp_wave" style="margin-top: '+
(Math.floor(0.5*this.targetDiv.clientHeight)-20)+'px;">');h=h+('\t<div class="rect1" style="background-color: '+f+'"></div>')+('\t<div class="rect2" style="background-color: '+f+'"></div>');h+='\t<div class="rect3" style="background-color: '+f+'"></div>';h+='\t<div class="rect4" style="background-color: '+f+'"></div>';h+='\t<div class="rect5" style="background-color: '+f+'"></div>';h+="</div>";this.percentDiv.innerHTML=h;this.percentDiv.setAttribute("id","preloader_"+this.targetDiv.id);this.targetDiv.appendChild(this.percentDiv)},
update:function(a){},destroy:function(){this.percentDiv.innerHTML="";this.percentDiv.style.display="none";this.targetDiv.removeChild(this.percentDiv);this.targetDiv.removeChild(this.backgroundDiv);this.targetDiv=this.percentDiv=this.backgroundDiv=null}};g.initialize(a,e.color1);return g},addClickOrTouchListener:function(a,e,b){this.isTouchDevice?void 0!==e.forTouch&&this.addEventSimple(a,e.forTouch,b):void 0!==e.forMouse&&this.addEventSimple(a,e.forMouse,b)},removeClickOrTouchListener:function(a,
e,b){this.isTouchDevice?this.removeEventSimple(a,e.forTouch,b):this.removeEventSimple(a,e.forMouse,b)},bind:function(a,e,b){return function(){e.apply(a,arguments)}},signum:function(a){return 0<a?1:0>a?-1:0},supportedBrowserCheck:function(){if(/MSIE (\d+\.\d+);/.test(navigator.userAgent)){var a=Number(RegExp.$1);8==a&&(this.isIE8=!0);9==a&&(this.isIE9=!0);return 8<=a}return!0},detectBrowser:function(){-1<navigator.userAgent.toLowerCase().indexOf("chrome")&&(this.isChrome=!0)},fullscreenBrowserCheck:function(){return document.fullscreenEnabled||
document.webkitFullscreenEnabled||document.mozFullScreenEnabled||document.msFullscreenEnabled?!0:!1},browserSupportsCSSProperty:function(a){var e=document.createElement("div");a=a.toLowerCase();if(void 0!=e.style[a])return!0;a=a.charAt(0).toUpperCase()+a.substr(1);for(var b=["Webkit","Moz","ms","O"],d=0;d<b.length;d++)if(void 0!=e.style[b[d]+a])return!0;return!1},isObjectEmpty:function(a){if(void 0===a)return!0;var e=Object.prototype.hasOwnProperty;if(a.length&&0<a.length)return!1;if(a.length&&0===
a.length)return!0;for(var b in a)if(e.call(a,b))return!1;return!0},launchFullscreen:function(a){a.requestFullscreen?a.requestFullscreen():a.mozRequestFullScreen?a.mozRequestFullScreen():a.webkitRequestFullscreen?a.webkitRequestFullscreen():a.msRequestFullscreen&&a.msRequestFullscreen()},exitFullscreen:function(a){document.exitFullscreen?document.exitFullscreen():document.cancelFullscreen?document.cancelFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.webkitCancelFullScreen?
document.webkitCancelFullScreen():document.msExitFullscreen&&document.msExitFullscreen()},isFullscreen:function(){return!!(document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement)},isInIframe:function(){try{return window.self!==window.top}catch(a){return!0}},addGlobalFunctions:function(){window.yofla_setColor=this.yofla_setColor;window.yofla_setLevel=this.yofla_setColor},yofla_setColor:function(a){var e,b=0;"string"===typeof a?0<=a.indexOf(",")?
(b=a.split(","),e=b[0],b=b[1]):b=parseInt(a):b=parseInt(a);(e=RotateTool.get(e))?e.setLevel(b):alert("Unable to locate 3DRT instance!")},detectCanvasSupport:function(){return!!document.createElement("canvas").getContext},detectCustomEventSupport:function(){try{return new CustomEvent("blank"),!0}catch(a){return!1}},baseName:function(a){var e=a.charAt(a.length-1);if("/"===e||"\\"===e)a=a.slice(0,-1);a=a.replace(/^.*[\/\\]/g,"");"string"===typeof suffix&&a.substr(a.length-suffix.length)==suffix&&(a=
a.substr(0,a.length-suffix.length));return a},isGAloaded:function(a){if("function"===typeof ga)return!0;if("undefined"!==typeof a&&!0!==this.gaCodeWritten){var e="auto";"localhost"==document.location.hostname&&(e={cookieDomain:"none"});(function(a,d,c,e,k,f,h){a.GoogleAnalyticsObject=k;a[k]=a[k]||function(){(a[k].q=a[k].q||[]).push(arguments)};a[k].l=1*new Date;f=d.createElement(c);h=d.getElementsByTagName(c)[0];f.async=1;f.src=e;h.parentNode.insertBefore(f,h)})(window,document,"script","//www.google-analytics.com/analytics.js",
"ga");ga("create",a,e);this.gaCodeWritten=!0}return!1},addPolyFills:function(){this.addIndexOf();this.addDatePolyFill()},addIndexOf:function(){Array.prototype.indexOf||(Array.prototype.indexOf=function(a,e){var b=this.length>>>0,d=Number(e)||0,d=0>d?Math.ceil(d):Math.floor(d);for(0>d&&(d+=b);d<b;d++)if(d in this&&this[d]===a)return d;return-1})},addDatePolyFill:function(){Date.now||(Date.now=function(){return(new Date).valueOf()})},getCurrentDomain:function(){var a=window.location!=window.parent.location?
document.referrer:document.location,e=document.createElement("a");e.href=a;return(a=e.hostname)&&4<a.length?(a=a.split("."),a=a.slice(-2).join(".")):""},Quad_easeOut:function(a,e,b,d){return-b*((a=a/d-1)*a*a*a-1)+e},pauseEvent:function(a){a.stopPropagation&&a.stopPropagation();a.preventDefault&&a.preventDefault();a.cancelBubble=!0;return a.returnValue=!1},XMLloader:function(){var a,e,b,d,c,g;this.loadXML=function(b,d,f,n){g=n;a=d;e=f;c=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP");
c.onreadystatechange=k;c.open("GET",b,!0);c.send("")};var k=function(){if(4==c.readyState&&(200==c.status||304==c.status)){if(e){var h=c.responseXML;b=[];f(h,0);for(i=b.length-1;0<=i;i--)nodeRef=b[i],nodeRef.parentNode.removeChild(nodeRef)}d=c.responseXML;"function"==typeof a?a.call(g,[d]):alert("undefined type of functionToCall")}},f=function(a,c){for(i=0;i<a.childNodes.length;i++)3!=a.childNodes[i].nodeType||/[^\t\n\r ]/.test(a.childNodes[i].data)||(b[b.length]=a.childNodes[i]),a.childNodes[i].hasChildNodes()&&
f(a.childNodes[i],i);i=c}},last:"none"};RotateTool.initialize();
